general.import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
decorations = "full"
title = "Alacritty"
dynamic_title = true
startup_mode = "Maximized"
opacity = 0.95
dynamic_padding = true

[scrolling]
history = 1000
multiplier = 3

[font]
size = 12.0

offset.x = 0
offset.y = 0

glyph_offset.x = 0
glyph_offset.y = 0

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[terminal.shell]
program = "/bin/fish"
args = []

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Alt"
action = "Copy"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
## Time in milliseconds between blinks, default 750
blink_interval = 650
## Time in seconds for cursor to "hold" its blink, default 5
blink_timeout = 5
## Thickness of cursor relative to cell width. 0.0 to 1.0, default 0.15
thickness = 0.15
## Render cursor as a hollow box when window loses focus
unfocused_hollow = true
## Block, Beam, Underline
style.shape = "Beam"
## Never, Off, On, Always
style.blinking = "Always"

vi_mode_style.shape = "Block"
vi_mode_style.blinking = "Never"
